[package]
name = "linamp"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.10.2", package = "gtk4", features = ["v4_18"] }
symphonia = { version = "0.5.5", features = [ "all" ]}
walkdir = "2.5.0"
